version: '3'

services:
  web:
    container_name: f-chess-web
    build:
      context: .
    ports:
      - "8888:8888"
    networks:
      - f-network
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: fchess
      MYSQL_USER: userchess
      MYSQL_PASSWORD: 123123
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - f-network
volumes:
  dbdata:
networks:
  f-network:
    driver: bridge