
version: '3'

services:
#  web:
#    container_name: f-chess-web
#    build:
#      context: .
#    networks:
#      - f-network
#    depends_on:
#      - db
  db:
    image: postgres:latest
    container_name: db
    environment:
#      MYSQL_ROOT_PASSWORD: 123123
#      MYSQL_DATABASE: fchess
      POSTGRES_USER: userchess
      POSTGRES_DB: fchess
      POSTGRES_PASSWORD: 123123
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgr-data:/data/postgres
    networks:
      - f-network
volumes:
  postgr-data:
networks:
  f-network:
    driver: bridge
