rt-server:
  port: 9092
  host: localhost
logging:
  level:
    com:
      example:
        fchess: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:6033/fchess?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
app:
  auth:
    tokenSecret: KMASKD9123BHAF123
