rt-server:
  port: 80
  host: 0.0.0.0
logging:
  level:
    com:
      example:
        fchess: debug
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://db/fchess
#    username: userchess
#    password: 123123
    url: ${HEROKU_POSTGRESQL_SILVER_JDBC_URL}
    username: ${HEROKU_POSTGRESQL_SILVER_JDBC_USERNAME}
    password: ${HEROKU_POSTGRESQL_SILVER_JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1095673906690-iq96bvknlgee4o4lpcgouhkjfopg7ucn.apps.googleusercontent.com
            clientSecret: qYBkFQtyM0q23xqHABlMYk-N
            redirectUri: "{baseUrl}/oauth2/authorize/callback/{registrationId}"
            scope:
              - email
              - profile
app:
  auth:
    tokenSecret: KMASKD9123BHAF123
  oauth2:
    authorizedRedirectUris:
       - http://localhost:3000/oauth2/redirect
server:
  port: 8888